package domain

import "time"

// ContractActivation is the idempotent contract-to-project handoff owned by the contract system.
type ContractActivation struct {
	ContractID string `json:"contract_id"`
	// ContractNumber 是面向用户展示的权威合同编号。滚动发布期间旧合同系统未携带时，
	// 项目管理以 ContractID 回退展示，但幂等键始终使用稳定的 ContractID + ContractVersion。
	ContractNumber  string `json:"contract_number,omitempty"`
	ContractVersion string `json:"contract_version"`
	ContractName    string `json:"contract_name"`
	Customer        string `json:"customer"`
	// CustomerID 是合同系统持有的客户标识；旧版调用方未携带时保持空，项目仍以名称记录客户。
	CustomerID              string            `json:"customer_id,omitempty"`
	EffectiveAt             time.Time         `json:"effective_at"`
	StampedContractUploaded bool              `json:"stamped_contract_uploaded"`
	Services                []ContractService `json:"services"`
}

type ContractService struct {
	SourceID    string `json:"source_id"`
	Name        string `json:"name"`
	Site        string `json:"site"`
	SiteCode    string `json:"site_code,omitempty"`
	Batch       string `json:"batch"`
	Category    string `json:"category"`
	System      string `json:"system"`
	SystemLevel string `json:"system_level"`
	Requirement string `json:"requirement"`
	TestMode    string `json:"test_mode"`
}

type DeliveryEvent struct {
	ID            string         `json:"id"`
	TenantID      string         `json:"-"`
	ProjectID     string         `json:"project_id"`
	ServiceItemID string         `json:"service_item_id,omitempty"`
	Type          string         `json:"type"`
	ActorUserID   string         `json:"actor_user_id"`
	Payload       map[string]any `json:"payload"`
	CreatedAt     time.Time      `json:"created_at"`
	// ClientOperationID is generated by the field client before an offline-capable
	// write. The database uses it to make reconnect retries idempotent.
	ClientOperationID string     `json:"client_operation_id,omitempty"`
	CapturedAt        *time.Time `json:"captured_at,omitempty"`
	// Notification is an internal transaction companion. It is persisted to the project outbox
	// together with the delivery event and is deliberately excluded from the audit event JSON.
	Notification *NotificationMessage `json:"-"`
}

type NotificationMessage struct {
	EventID        string    `json:"event_id"`
	EventType      string    `json:"event_type"`
	Scope          string    `json:"notification_scope"`
	Priority       string    `json:"priority"`
	Title          string    `json:"title"`
	Content        string    `json:"content"`
	ReferenceType  string    `json:"reference_type"`
	ReferenceID    string    `json:"reference_id"`
	Recipients     []string  `json:"recipient_user_ids"`
	OccurredAt     time.Time `json:"occurred_at"`
	IdempotencyKey string    `json:"idempotency_key"`
}

type NotificationOutboxItem struct {
	ID         uint64              `json:"id"`
	Message    NotificationMessage `json:"message"`
	RetryCount uint                `json:"retry_count"`
}

type Capability struct {
	ID           string `json:"id"`
	TenantID     string `json:"-"`
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	ResourceName string `json:"resource_name"`
	// UserID 是人员能力档案关联的平台 user_id：实施计划的人员行既可按档案编号、
	// 也可按平台 user_id 提交，服务端统一解析到档案行，消除人员标识双轨制。
	// 仅 PERSON 类型有意义；设备行保持空。
	UserID     string    `json:"user_id,omitempty"`
	Codes      []string  `json:"codes"`
	ValidFrom  time.Time `json:"valid_from"`
	ValidUntil time.Time `json:"valid_until"`
	Status     string    `json:"status"`
	// EffectiveStatus 是结合手工启停状态与设备检定有效期计算出的当前业务状态。
	// Status 仍保留持久化值，避免读取列表后编辑记录时把派生状态误写回数据库。
	EffectiveStatus string `json:"effective_status"`
	StatusReason    string `json:"status_reason,omitempty"`
	// UsageScope 为 ANY（可借出）或 COMPANY_ONLY（仅在公司使用，不可借出）。
	UsageScope string `json:"usage_scope"`
	// IdentityStatus 是人员档案与基础平台负责人目录的复核结果：
	// ACTIVE（目录中存在）/ MISSING（已离职或查无此人）/ UNLINKED（历史档案未关联 user_id）。
	// 资质档案在本系统维护，但"这个人是否真实存在"只能由基础平台回答。
	IdentityStatus string `json:"identity_status,omitempty"`
	// IdentityCheckedAt 是最近一次回基础平台复核的时间；零值表示从未复核。
	IdentityCheckedAt time.Time `json:"identity_checked_at,omitempty"`
	// Presence 是派生状态：IN_COMPANY / OUT_OF_COMPANY（借出中）。仅设备有意义。
	Presence string `json:"presence,omitempty"`
	// BorrowedBy 在借出中时说明占用方（项目号）；BorrowedServiceItemID 供设备维护页发起归还。
	BorrowedBy            string    `json:"borrowed_by,omitempty"`
	BorrowedServiceItemID string    `json:"borrowed_service_item_id,omitempty"`
	BorrowedWindow        string    `json:"borrowed_window,omitempty"`
	UpdatedAt             time.Time `json:"updated_at"`
}

// QualifiedPersonnel is the assignment-facing projection of a PERSON capability.
// UserID remains the durable workflow assignee identifier; ResourceID is the
// human-readable qualification-ledger number used for audit and display.
type QualifiedPersonnel struct {
	UserID         string   `json:"user_id"`
	ResourceID     string   `json:"resource_id"`
	DisplayName    string   `json:"display_name"`
	Codes          []string `json:"codes"`
	IdentityStatus string   `json:"identity_status"`
}

type QualifiedPersonnelPage struct {
	Items    []QualifiedPersonnel `json:"items"`
	Page     int                  `json:"page"`
	PageSize int                  `json:"page_size"`
	Total    int64                `json:"total"`
}

// 设备使用范围：可借出 / 仅在公司使用。
const (
	EquipmentUsageAny         = "ANY"
	EquipmentUsageCompanyOnly = "COMPANY_ONLY"
)

// 设备在位状态：由占用时段派生，不落库。
const (
	EquipmentPresenceInCompany    = "IN_COMPANY"
	EquipmentPresenceOutOfCompany = "OUT_OF_COMPANY"
)

type DecompositionAdjustmentInput struct {
	Reason               string            `json:"reason"`
	SupplementContractID string            `json:"supplement_contract_id"`
	Items                []ContractService `json:"items"`
}

type TeamAssignmentInput struct {
	TeamLeadID string `json:"team_lead_id"`
	// ExpectedVersion 是客户端读取到的服务项版本；非 0 且与服务端不一致时返回 409，
	// 让"我基于的是旧版本"被显式发现，而不是静默覆盖对方刚提交的修改。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// AssignmentRevokeInput 用于待分配阶段的受控撤销。原因不是可选备注：撤销会改变
// 已通知的责任链，必须在交付事件中留下可审计的业务依据。
type AssignmentRevokeInput struct {
	Reason          string `json:"reason"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// PhaseRevokeInput 用于尚未进入现场的计划/准备补偿；原因与版本保证撤销可审计且不覆盖新状态。
type PhaseRevokeInput struct {
	Reason          string `json:"reason"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// RollbackRequestInput/DecisionInput 用于现场与报告阶段的双人复核补偿。现场证据和报告事件
// 永不删除；批准只把服务项重新打开，并把请求及审批分别写成不可变事件。
type RollbackRequestInput struct {
	Kind            string `json:"kind"`
	Reason          string `json:"reason"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}
type RollbackDecisionInput struct {
	Decision        string `json:"decision"`
	Comment         string `json:"comment"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}
type RollbackWithdrawInput struct {
	Reason string `json:"reason"`
}
type ReportCorrectionRequestInput struct {
	Reason          string `json:"reason"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}
type ReportCorrectionDecisionInput struct {
	Decision        string `json:"decision"`
	Comment         string `json:"comment"`
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// ExecutionAssignmentInput 是团队负责人指派项目经理与实施工程师的输入。
// 设备清单已在「实施准备」阶段登记，不再随指派提交。
type ExecutionAssignmentInput struct {
	ProjectManagerID string   `json:"project_manager_id"`
	EngineerIDs      []string `json:"engineer_ids"`
	RequiredCodes    []string `json:"required_codes"`
	// ExpectedVersion 语义同 TeamAssignmentInput：不匹配即 409 冲突。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// PlanResourceInput 是实施计划提交时的人员/设备行：只接受资源标识与使用时段，
// 名称、资质与有效期由服务端从能力档案解析，避免客户端伪造派工快照。
type PlanResourceInput struct {
	ResourceType string `json:"resource_type"`
	ResourceID   string `json:"resource_id"`
	WindowStart  string `json:"window_start,omitempty"`
	WindowEnd    string `json:"window_end,omitempty"`
	Note         string `json:"note,omitempty"`
}

// PlanResource 是实施计划里的人员/设备清单行，资质与有效期在发布计划时快照，
// 让已发布的计划保留当时的派工依据。
type PlanResource struct {
	ResourceType string   `json:"resource_type"`
	ResourceID   string   `json:"resource_id"`
	ResourceName string   `json:"resource_name"`
	Codes        []string `json:"codes"`
	ValidUntil   string   `json:"valid_until,omitempty"`
	WindowStart  string   `json:"window_start,omitempty"`
	WindowEnd    string   `json:"window_end,omitempty"`
	Note         string   `json:"note,omitempty"`
	// ReturnedAt 为归还时间；归还后的设备行保留历史，但不再占用设备、也不再算"不在公司"。
	ReturnedAt string `json:"returned_at,omitempty"`
}

type ImplementationPlanInput struct {
	PlannedStart        string `json:"planned_start"`
	PlannedEnd          string `json:"planned_end"`
	SitePlan            string `json:"site_plan"`
	PenetrationTestPlan string `json:"penetration_test_plan"`
	AuthDocNo           string `json:"auth_doc_no"`
	AuthStart           string `json:"auth_start"`
	AuthEnd             string `json:"auth_end"`
	AuthScope           string `json:"auth_scope"`
	TestScope           string `json:"test_scope"`
	TestWindow          string `json:"test_window"`
	EmergencyContact    string `json:"emergency_contact"`
	RollbackPlan        string `json:"rollback_plan"`
	// Personnel 是现场实施的人员清单；至少一名人员才能发布计划。
	// 设备清单在「实施准备」阶段提交，计划阶段不再选择设备。
	Personnel []PlanResourceInput `json:"personnel"`
	// ExpectedVersion 语义同 TeamAssignmentInput：不匹配即 409 冲突。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// ImplementationPlan 是与服务项绑定的实施计划读写模型，包含渗透测试专项合规要素。
type ImplementationPlan struct {
	PlannedStart        string         `json:"planned_start,omitempty"`
	PlannedEnd          string         `json:"planned_end,omitempty"`
	SitePlan            string         `json:"site_plan,omitempty"`
	PenetrationTestPlan string         `json:"penetration_test_plan,omitempty"`
	AuthDocNo           string         `json:"auth_doc_no,omitempty"`
	AuthStart           string         `json:"auth_start,omitempty"`
	AuthEnd             string         `json:"auth_end,omitempty"`
	AuthScope           string         `json:"auth_scope,omitempty"`
	TestScope           string         `json:"test_scope,omitempty"`
	TestWindow          string         `json:"test_window,omitempty"`
	EmergencyContact    string         `json:"emergency_contact,omitempty"`
	RollbackPlan        string         `json:"rollback_plan,omitempty"`
	Personnel           []PlanResource `json:"personnel"`
	Equipment           []PlanResource `json:"equipment"`
}

// EquipmentReservation 是一条设备占用记录，用于「实施准备」阶段判断设备在某段时间内
// 是否已被其他服务项占用，并向界面解释占用方。
type EquipmentReservation struct {
	ServiceItemID string `json:"service_item_id"`
	ProjectID     string `json:"project_id"`
	Customer      string `json:"customer,omitempty"`
	ResourceID    string `json:"resource_id"`
	ResourceName  string `json:"resource_name"`
	WindowStart   string `json:"window_start"`
	WindowEnd     string `json:"window_end"`
}

type SpecialMethodReviewInput struct {
	Decision string `json:"decision"`
	Comment  string `json:"comment"`
}

type ReportStatusInput struct {
	Phase string `json:"phase"`
	// ExpectedVersion 语义同 TeamAssignmentInput：不匹配即 409 冲突。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

type ReportArtifactInput struct {
	FileID   string `json:"file_id"`
	FileName string `json:"file_name"`
	MIME     string `json:"mime"`
	Size     uint64 `json:"size"`
	SHA256   string `json:"sha256"`
}

const (
	TravelModeNoTravel = "NO_TRAVEL"
	TravelModeExisting = "EXISTING"
	TravelModeNew      = "NEW"
)

// TravelArrangementInput 使用业务可读信息描述行程。ReferenceEventID 只用于关联本项目中
// 已登记的行程，避免让用户重新识别或抄写内部编号；NEW 模式的编号由服务端生成。
type TravelArrangementInput struct {
	Mode              string   `json:"mode"`
	ReferenceEventID  string   `json:"reference_event_id,omitempty"`
	RequestID         string   `json:"request_id,omitempty"`
	NoTravelReason    string   `json:"no_travel_reason,omitempty"`
	Origin            string   `json:"origin,omitempty"`
	Destination       string   `json:"destination,omitempty"`
	DepartureDate     string   `json:"departure_date,omitempty"`
	ReturnDate        string   `json:"return_date,omitempty"`
	Transport         string   `json:"transport,omitempty"`
	AccommodationNeed string   `json:"accommodation_need,omitempty"`
	TravelerIDs       []string `json:"traveler_ids,omitempty"`
}

// PreparationInput 是实施准备提交的内容。设备申领不再是自由文本：设备清单
// （Equipment）本身就说明申领了哪些设备、在什么时段使用，因此不再单列申领单号。
type PreparationInput struct {
	// TravelRequestID 仅为旧客户端滚动兼容；新客户端必须提交 Travel。
	TravelRequestID string                 `json:"travel_request_id,omitempty"`
	Travel          TravelArrangementInput `json:"travel"`
	Notes           string                 `json:"notes"`
	// ExpectedVersion 语义同 TeamAssignmentInput：不匹配即 409 冲突。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
	// Equipment 是实施准备确定的设备清单；每行带使用时段，服务端按占用区间硬拦重叠。
	Equipment []PlanResourceInput `json:"equipment"`
}

type FieldRecordInput struct {
	RawData     string `json:"raw_data"`
	Environment string `json:"environment"`
	// EvidenceFiles are immutable file-gateway receipts. EvidenceURLs remains accepted only for
	// backward-compatible request decoding and is rejected by the application service: a URL is
	// not durable evidence and cannot prove hash, size or gateway ownership.
	EvidenceFiles     []ReportArtifactInput `json:"evidence_files"`
	EvidenceURLs      []string              `json:"evidence_urls"`
	ClientOperationID string                `json:"client_operation_id,omitempty"`
	CapturedAt        string                `json:"captured_at,omitempty"`
	// ExpectedVersion 语义同 TeamAssignmentInput：不匹配即 409 冲突。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

// FieldCheckInInput records the engineer's observed position. Coordinates are
// evidence, not authorization: the actor still comes exclusively from the
// authenticated principal.
type FieldCheckInInput struct {
	Latitude          float64 `json:"latitude"`
	Longitude         float64 `json:"longitude"`
	AccuracyMeters    float64 `json:"accuracy_meters"`
	DeviationReason   string  `json:"deviation_reason,omitempty"`
	ClientOperationID string  `json:"client_operation_id"`
	CapturedAt        string  `json:"captured_at"`
	ExpectedVersion   uint64  `json:"expected_version,omitempty"`
}

// FieldSignatureInput binds an immutable file-gateway receipt to the signer,
// service item and capture time. Signature bytes never pass through this JSON API.
type FieldSignatureInput struct {
	SignatureFile     ReportArtifactInput `json:"signature_file"`
	ClientOperationID string              `json:"client_operation_id"`
	CapturedAt        string              `json:"captured_at"`
	ExpectedVersion   uint64              `json:"expected_version,omitempty"`
}

// FieldCompletionInput allows an authorized operator to acknowledge genuinely
// unavailable evidence. The repository still calculates missing evidence from
// immutable events; clients cannot claim that evidence exists.
type FieldCompletionInput struct {
	IncompleteReason string `json:"incomplete_reason,omitempty"`
}

type FieldStartInput struct {
	// ExpectedVersion 防止项目经理基于过期页面重复开始现场测评。
	ExpectedVersion uint64 `json:"expected_version,omitempty"`
}

type DeviationInput struct {
	Description   string                `json:"description"`
	Severity      string                `json:"severity"`
	EvidenceFiles []ReportArtifactInput `json:"evidence_files"`
	EvidenceURL   string                `json:"evidence_url"`
}

type DeviationReviewInput struct {
	Decision string `json:"decision"`
	Comment  string `json:"comment"`
}

type ConflictCheckResult struct {
	Passed    bool     `json:"passed"`
	Conflicts []string `json:"conflicts"`
}

// 人员档案身份复核状态：资质档案由本系统维护，但"这个人是否真实存在"必须回基础平台核对。
const (
	IdentityStatusActive   = "ACTIVE"
	IdentityStatusMissing  = "MISSING"
	IdentityStatusUnlinked = "UNLINKED"
)
